name: ecuagenera-notifier

on:
  schedule:
    - cron:  '* * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Runs script
      - name: Run a one-line script
        run: python3 src/opt/ecuagenera-notifier/ecuagenera_notifier.py
